description = "Create a git commit and push to remote repository"
prompt = """
Based on the following changes, create a single git commit and push it to the remote repository.

- Current git status:
!{git status}

- Current git diff (staged and unstaged changes):
!{git diff HEAD}

- Current branch:
!{git branch --show-current}

- Recent commits:
!{git log --oneline -10}
"""